"""initial schema

Revision ID: b6e14740493f
Revises: 
Create Date: 2026-09-26 02:08:26.970592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6e14740493f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('has_ambulance', sa.Boolean(), nullable=True),
    sa.Column('has_maternity', sa.Boolean(), nullable=True),
    sa.Column('has_csection', sa.Boolean(), nullable=True),
    sa.Column('referral_capacity', sa.Boolean(), nullable=True),
    sa.Column('is_waiting_home', sa.Boolean(), nullable=True),
    sa.Column('waiting_capacity', sa.Integer(), nullable=True),
    sa.Column('occupied_beds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maternal_waiting_centers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('occupied_beds', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('has_ambulance', sa.Boolean(), nullable=True),
    sa.Column('distance_to_emergency_facility_km', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=True),
    sa.Column('patient_code', sa.String(length=50), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gestation_weeks', sa.Integer(), nullable=True),
    sa.Column('gravida', sa.Integer(), nullable=True),
    sa.Column('para', sa.Integer(), nullable=True),
    sa.Column('previous_csection', sa.Boolean(), nullable=True),
    sa.Column('multiple_pregnancy', sa.Boolean(), nullable=True),
    sa.Column('known_conditions', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('enrollment_date', sa.DateTime(), nullable=True),
    sa.Column('village', sa.String(length=100), nullable=True),
    sa.Column('distance_to_facility_km', sa.Float(), nullable=True),
    sa.Column('has_transport', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('facility_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('access_risk_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('distance_to_facility_km', sa.Float(), nullable=True),
    sa.Column('transport_available', sa.Boolean(), nullable=True),
    sa.Column('previous_complications', sa.Boolean(), nullable=True),
    sa.Column('gestation_weeks', sa.Integer(), nullable=True),
    sa.Column('predicted_travel_time_minutes', sa.Integer(), nullable=True),
    sa.Column('access_risk_level', sa.String(length=20), nullable=True),
    sa.Column('recommended_waiting_center_id', sa.UUID(), nullable=True),
    sa.Column('recommended_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['recommended_waiting_center_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referral_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('source_facility_id', sa.UUID(), nullable=True),
    sa.Column('destination_facility_id', sa.UUID(), nullable=True),
    sa.Column('referral_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('arrival_time', sa.DateTime(), nullable=True),
    sa.Column('referral_status', sa.String(length=20), nullable=True),
    sa.Column('referral_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['destination_facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['source_facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('midwife_id', sa.UUID(), nullable=True),
    sa.Column('assessment_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('systolic_bp', sa.Integer(), nullable=True),
    sa.Column('diastolic_bp', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('bleeding_estimate_ml', sa.Integer(), nullable=True),
    sa.Column('headache_severity', sa.Integer(), nullable=True),
    sa.Column('visual_changes', sa.Boolean(), nullable=True),
    sa.Column('abdominal_pain_severity', sa.Integer(), nullable=True),
    sa.Column('foul_discharge', sa.Boolean(), nullable=True),
    sa.Column('labour_hours', sa.Float(), nullable=True),
    sa.Column('fever', sa.Boolean(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('primary_condition', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('explanation_text', sa.Text(), nullable=True),
    sa.Column('shap_values', sa.JSON(), nullable=True),
    sa.Column('actions_taken', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('referral_initiated', sa.Boolean(), nullable=True),
    sa.Column('referral_facility_id', sa.UUID(), nullable=True),
    sa.Column('patient_outcome', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['midwife_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['referral_facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health_economics_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_assessment_id', sa.UUID(), nullable=True),
    sa.Column('estimated_cost_standard_care', sa.Integer(), nullable=True),
    sa.Column('estimated_dalys_standard_care', sa.Float(), nullable=True),
    sa.Column('estimated_cost_ai_assisted', sa.Integer(), nullable=True),
    sa.Column('estimated_dalys_averted', sa.Float(), nullable=True),
    sa.Column('cost_savings', sa.Integer(), nullable=True),
    sa.Column('dalys_averted_total', sa.Float(), nullable=True),
    sa.Column('discount_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['risk_assessment_id'], ['risk_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('health_economics_events')
    op.drop_table('risk_assessments')
    op.drop_table('referral_events')
    op.drop_table('access_risk_assessments')
    op.drop_table('users')
    op.drop_table('patients')
    op.drop_table('maternal_waiting_centers')
    op.drop_table('facilities')
    # ### end Alembic commands ###
